events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        
        # Route API traffic to Backend
        location /api/ {
            proxy_pass http://backend:8005/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route Swagger Docs to Backend
        location /docs {
            proxy_pass http://backend:8005/docs;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        location /openapi.json {
            proxy_pass http://backend:8005/openapi.json;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Route all other traffic to Frontend
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
